[project]
name = "eiv-igp-jax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "arviz>=0.21.0",
    "jax>=0.6.0",
    "matplotlib>=3.10.3",
    "numpyro>=0.18.0",
    "optax>=0.2.4",
    "pandas>=2.2.3",
]
